[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]
aptPkgs = ["default-mysql-client"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
